<a href="https://colab.research.google.com/github/Ganesh9100/Workshop-Data-Analysis/blob/master/(WS453)_Assignment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Data Analysis Using Python Assignment-01***


**-----------------------------------------------------------------------**


**Name        :  GaneshRaj V**

**WS Number   : *WS453***

**College Name: Vel High-Tech Dr.RR and Dr.SR Engineering College**


**---------------------------------------------------------------------------**



 
1.
**Create two 2D array with 30 elements. Give array name array1, array2.**

**Do the element-wise comparison of array1, array2.**

**[Hint: less, less than, greater, greater than]**

In [ ]:
import numpy as np

In [ ]:
# Creating  two 2-D array of 30 elements with 2 and 4 as value respectively

array1=np.full([6,5],2)
print("Array_1")
print(array1)

print("------------------------")

array2=np.full([6,5],4)
print("Array_2")
print(array2)



Array_1
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
------------------------
Array_2
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [ ]:

""" 
HERE WE ARE Do Element-Wise COMPARISION Array_1 and Array_2 

Arguments:
(arg1) :  type(Array)   ( array1 ) 
(arg2) :  type(Array)   ( array2 ) 

Returns:
compare's the given Array's and return's in bool 

"""


def is_equal(array1,array2):
  print("IS Array_1 AND Array_2 ARE EQUAL")
  print()
  return array1 == array2
    
def is_greater(array1,array2):
  print("IS array_1 IS GREATER THAN Array_2")
  print()
  return array1 > array2
    
def is_smaller(array1,array2):
  print("IS Array_1 IS SMALLER THAN Array_2")
  print()
  return array1 < array2
    

print(is_equal(array1,array2))
print("------------------------------------------------------")

print(is_greater(array1,array2))
print("------------------------------------------------------")

print(is_smaller(array1,array2))
print("------------------------------------------------------")

IS Array_1 AND Array_2 ARE EQUAL

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
------------------------------------------------------
IS array_1 IS GREATER THAN Array_2

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
------------------------------------------------------
IS Array_1 IS SMALLER THAN Array_2

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
------------------------------------------------------


In [ ]:
"""
I have created the Modular Function .
HERE WE Compare the Array with a specific Number ( Element-Wise )

Arguments:
(arg1) :  Array ( array1 or array2) Change near print statement specified below 
(arg2) :  Number ( This is the input which user has to specify )

Returns:
compare's the given argument's and return's in bool 
"""





def is_Equal(array,number):
  print("Is array is EQUAL to Number")
  print()
  return array == number
       
def Greater(array,number):
  print("Is array Greater Than Number")
  print()
  return array  >  number

def Smaller(array,number):
  print("Is array Smaller Than Number")
  print()
  return array  <  array2

n=int(input("Enter the number to Compare"))

# here i have called the function with array 1 , we can change from array 1 to array 2
print(is_Equal(array1,n))
print("------------------------------------------------------")
print(Greater(array1,n))
print("------------------------------------------------------")
print(Smaller(array1,n))
print("------------------------------------------------------")

Enter the number to Compare  5
Is array is EQUAL to Number

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
------------------------------------------------------
Is array Greater Than Number

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
------------------------------------------------------
Is array Smaller Than Number

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
------------------------------------------------------


2.

**Use arange function to create two 2D array with 20 elements.**

**Give array name
array3, array4.**

**Do element-wise comparison of array3, array4.**

**[Hint:Equal, not Equal]**

In [ ]:
# Creating  two 2-D array using arange, with 20 elements 

array3=np.arange(20).reshape(4, 5)      #reshaping to 2-D    and  elements are in the range of ( 0-20 )
print("Array_3")
print(array3)

print("------------------------")


array4=np.arange(10,30).reshape(4, 5)   #reshaping with 2-D  and  elements are in the range of ( 10-30 )
print("Array_4")
print()
print(array4)


Array_3
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
------------------------
Array_4

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [ ]:

""" 
HERE WE ARE Do Element-Wise COMPARISION Array_3 and Array_4 

Arguments:
(arg1) :  type(Array)   ( array3 ) 
(arg2) :  type(Array)   ( array4 ) 

Returns:
compare's the given Array's and return's in bool 

"""



def is_equal(array3,array4):                      # Returns True if both the arrays are equal else False
  print("IS THE Array 3 AND Array 4 ARE EQUAL")
  print()
  return array3 == array4
    
def is_greater(array3,array4):                    # Returns True if array_3 is GREATER THAN array 4
  print("IS THE Array 3 IS GREATER THAN Array 4")
  print()
  return array3 > array4
    
def is_smaller(array3,array4):                     # Returns True if array_3 is SMALLER THAN array 4
  print("IS THE Array 3 IS SMALLER THAN Array 4")
  print()
  return array3  < array4
    

print(is_equal(array3,array4))
print("------------------------------------------------------")

print(is_greater(array3,array4))
print("------------------------------------------------------")

print(is_smaller(array3,array4))
print("------------------------------------------------------")

IS THE Array 3 AND Array 4 ARE EQUAL

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
------------------------------------------------------
IS THE Array 3 IS GREATER THAN Array 4

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
------------------------------------------------------
IS THE Array 3 IS SMALLER THAN Array 4

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
------------------------------------------------------


3.

**Create a full 1D array with size 16 and fill value with 20 and give array name array5.**

**Check the size of memory occupied by the array5.**

In [ ]:
array5=np.full(16,20)           # Creating 1-D array of 20 elements with default value 20
print("Size of the array_5   :",array5.size,"bytes")
print("Array_5")
print(array5)

Size of the array_5   : 16 bytes
Array_5
[20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20]


In [ ]:
print("Memory occupied by the array 5 in bytes: ", array5.itemsize * array5.size) 

Memory occupied by the array 5 in bytes:  128


**4**

**Create a single array(array6) with values ranging from 26 to 50 with float type**

**create another array (array7) with values ranging from 51 to 75 with float type.**

**Check the dimension, shape and size of given two arrays.**
 
**Find the dot product of array6 and array7 and store values in array8.**

In [ ]:
arr1=np.arange(26,50)                # Storing 1-d array  of range (26-50) in arr1
array6=np.array(arr1,dtype='float')  #Changing the array type and storing in array6 variable


print("ARRAY_6")
print(array6)
print()
print("Dimension of array_6     :",array6.ndim,"-Dimension")
print("Shape of array_6         :",array6.shape)
print("Size of array_6          :",array6.size,"bytes")
print("Total memory of array_6  :",array6.size * array6.itemsize,"bytes")

ARRAY_6
[26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43.
 44. 45. 46. 47. 48. 49.]

Dimension of array_6     : 1 -Dimension
Shape of array_6         : (24,)
Size of array_6          : 24 bytes
Total memory of array_6  : 192 bytes


In [ ]:
arr2=np.arange(51,75)                # Storing 1-d array of range (51-75) in arr2
array7=np.array(arr2,dtype='float')  #Changing the array type and storing in array7 variable

print("ARRAY_7")
print(array7)
print()
print("Dimension of array_7     :",array7.ndim,"-Dimension")
print("Shape of array_7         :",array7.shape)
print("Size of array_7          :",array7.size,"bytes")
print("Total memory of array_7  :",array7.size  * array7.itemsize,"bytes")

ARRAY_7
[51. 52. 53. 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68.
 69. 70. 71. 72. 73. 74.]

Dimension of array_7     : 1 -Dimension
Shape of array_7         : (24,)
Size of array_7          : 24 bytes
Total memory of array_7  : 192 bytes


In [ ]:
array8=np.dot(array6,array7)
print("The dot-product of ARRAY 6 and ARRAY 7 is  :  ",array_8)


The dot-product of ARRAY 6 and ARRAY 7 is  :   57400.0


**5.**

**Create two 2-D array with shape (5,5) with name array9 and array10.**

**Apply any
five array arithmetic operations** 

**Any five array aggregate functions on array9
and array10.**

In [ ]:

array9=np.full([5,5],10)          # Creating array of shape (5,5) with value 10 
print("ARRAY 9")
print(array9)
print("---------------------------------------------------------")

array10=np.full([5,5],20)         # Creating array of shape (5,5) with value 20
print("ARRAY 10")
print()
print(array10)

ARRAY 9
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
---------------------------------------------------------
ARRAY 10

[[20 20 20 20 20]
 [20 20 20 20 20]
 [20 20 20 20 20]
 [20 20 20 20 20]
 [20 20 20 20 20]]


In [ ]:

""" 
This below function is Modular ,this function help's 
to do both Array Arithmetic operation as well as 
Arithmetic Operation with Array and Numbers 

Arguments:
(arg1) :  type(Array)   ( array3 ) 
(arg2) :  type(Array)   ( array4 )   or type(int)  (Number) given by User

Function : Print the Arithmetic Operations

Returns:
  None 

"""

def add(arr1,arr2):
  print(np.add(arr1,arr2))

def sub(arr1,arr2):
  print(np.subtract(arr1,arr2))

def multiply(arr1,arr2):
  print(np.multiply(arr1,arr2))

def divide(arr1,arr2):
  print(np.divide(arr1,arr2))



In [ ]:
print("Addition of Array_9 and Array_10")
add(array9,array10)
print()
print("Subraction of Array_9 from Array_10")
sub(array9,array10)
print()
print("Multiplication of Array_9 with Array_10")
multiply(array9,array10)
print()
print("Division of Array_9 by Array_10")
divide(array9,array10)
print()


Addition of Array_9 and Array_10
[[30 30 30 30 30]
 [30 30 30 30 30]
 [30 30 30 30 30]
 [30 30 30 30 30]
 [30 30 30 30 30]]

Subraction of Array_9 from Array_10
[[-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]]

Multiplication of Array_9 with Array_10
[[200 200 200 200 200]
 [200 200 200 200 200]
 [200 200 200 200 200]
 [200 200 200 200 200]
 [200 200 200 200 200]]

Division of Array_9 by Array_10
[[0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]]



In [ ]:
N=int(input("Enter the Number to do Arithemetic Operations with Array"))

Enter the Number to do Arithemetic Operations with Array  10


In [ ]:

#Below code will Call the respective Modular Function defined above

# Arithmetic Operations of both (Array 9 and Array 10) with a Number
# since I have created a modular function ,I have used Array 9 with a Number 
# you can change to Array 10 and implement 


print("Addition of Array 9 and Number")
add(array9,N)
print()

print("Subraction of Array 9 from Number")
sub(array9,N)
print()

print("Multiplication of Array 9 with Number")
multiply(array9,N)
print()

print("Division of Array 9 by Number")
divide(array9,N)
print()

Addition of Array 9 and Number
[[20 20 20 20 20]
 [20 20 20 20 20]
 [20 20 20 20 20]
 [20 20 20 20 20]
 [20 20 20 20 20]]

Subraction of Array 9 from Number
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Multiplication of Array 9 with Number
[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]

Division of Array 9 by Number
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



In [ ]:

#Below code will Call the respective Modular Function 

# Arithmetic Operations with Array 10 and a Number

print("Addition of Array_10 and Number")
add(array10,N)
print()
print("Subraction of Array_10 from Number")
sub(array10,N)
print()
print("Multiplication of Array_10 with Number")
multiply(array10,N)
print()
print("Division of Array_10 by Number")
divide(array10,N)
print()

Addition of Array_10 and Number
[[30 30 30 30 30]
 [30 30 30 30 30]
 [30 30 30 30 30]
 [30 30 30 30 30]
 [30 30 30 30 30]]

Subraction of Array_10 from Number
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]

Multiplication of Array_10 with Number
[[200 200 200 200 200]
 [200 200 200 200 200]
 [200 200 200 200 200]
 [200 200 200 200 200]
 [200 200 200 200 200]]

Division of Array_10 by Number
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]



In [ ]:

# Aggregate Functions with Array 9 

print("Smallest element in the array_9          :",array9.min())
print("Largest element in the array_9           :",array9.max())
print("Variance of Array_9                      :",array9.var())
print("Sum of element's in the array_9          :",array9.sum())
print("Mean value of array_9                    :",array9.mean())

Smallest element in the array_9          : 10
Largest element in the array_9           : 10
Variance of Array_9                      : 0.0
Sum of element's in the array_9          : 250
Mean value of array_9                    : 10.0


In [ ]:
# Aggregate Functions with Array 10

print("Smallest element in the array_10          :",array10.min())
print("Largest element in the array_10           :",array10.max())
print("Variance of Array_10                      :",array10.var())
print("Sum of element's in the array_10          :",array10.sum())
print("Mean value of array_10                    :",array9.mean())

Smallest element in the array_10          : 20
Largest element in the array_10           : 20
Variance of Array_10                      : 0.0
Sum of element's in the array_10          : 500
Mean value of array_10                    : 10.0


**Thank You**